

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_22 = Integer(22); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_9 = Integer(9)
import os

counterexample_file = open('./temp.txt', 'w')
for file_name in os.listdir('./alldegphi'):
	file = open('./alldegphi/{}'.format(file_name))
	for line in file.readlines():
		split = line.split(' ')
		for prime in factor(int(split[_sage_const_0 ])):
			if prime[_sage_const_0 ] < _sage_const_22 :
				continue
			E = EllipticCurve(split[_sage_const_0 ] + split[_sage_const_1 ] + split[_sage_const_2 ])
			if E.j_invariant() == _sage_const_0 :
				continue
			j_inv = E.j_invariant().valuation(prime[_sage_const_0 ])
			if not E.has_split_multiplicative_reduction(prime[_sage_const_0 ]):
				continue
			if j_inv == _sage_const_0 :
				continue
			factors = factor(prime[_sage_const_0 ]-_sage_const_1 )
			for ell in factors:
				if ell[_sage_const_0 ] < _sage_const_9 :
					continue
				modular_degree = E.modular_degree()
#				if gcd(ell[0], modular_degree) > 1:
#					continue
				if gcd(ell[_sage_const_0 ], Integer(j_inv)) > _sage_const_1 :
					print(str(split[_sage_const_0 ]) + str(split[_sage_const_1 ]) + str(split[_sage_const_2 ]) + ' ' + str(prime[_sage_const_0 ]) + ' ' + str(ell[_sage_const_0 ]) + ' ' + str(j_inv))
					write_text = str(split[_sage_const_0 ]) + str(split[_sage_const_1 ]) + str(split[_sage_const_2 ]) + ' ' + str(prime[_sage_const_0 ]) + ' ' + str(ell[_sage_const_0 ]) + ' ' + str(j_inv) + '\n'
					counterexample_file.write(write_text)
	
	file.close()
counterxample_file.close()

